# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FPGA/CHOICE-PUF/CHOICE_design/CHOICE_design.srcs/sources_1/bd/design_pynq/ip/design_pynq_axi_dma_0_0/design_pynq_axi_dma_0_0.xci
# IP: The module: 'design_pynq_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/CHOICE-PUF/CHOICE_design/CHOICE_design.gen/sources_1/bd/design_pynq/ip/design_pynq_axi_dma_0_0/design_pynq_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_pynq_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/CHOICE-PUF/CHOICE_design/CHOICE_design.gen/sources_1/bd/design_pynq/ip/design_pynq_axi_dma_0_0/design_pynq_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_pynq_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/CHOICE-PUF/CHOICE_design/CHOICE_design.gen/sources_1/bd/design_pynq/ip/design_pynq_axi_dma_0_0/design_pynq_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_pynq_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/FPGA/CHOICE-PUF/CHOICE_design/CHOICE_design.srcs/sources_1/bd/design_pynq/ip/design_pynq_axi_dma_0_0/design_pynq_axi_dma_0_0.xci
# IP: The module: 'design_pynq_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/CHOICE-PUF/CHOICE_design/CHOICE_design.gen/sources_1/bd/design_pynq/ip/design_pynq_axi_dma_0_0/design_pynq_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_pynq_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/CHOICE-PUF/CHOICE_design/CHOICE_design.gen/sources_1/bd/design_pynq/ip/design_pynq_axi_dma_0_0/design_pynq_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_pynq_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/CHOICE-PUF/CHOICE_design/CHOICE_design.gen/sources_1/bd/design_pynq/ip/design_pynq_axi_dma_0_0/design_pynq_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_pynq_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
