# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/base_constraints.xdc

# XDC: imports/constraints/PUF_constraints.xdc

# XDC: new/choice_pynq.xdc

# Block Designs: bd/design_pynq/design_pynq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pynq || ORIG_REF_NAME==design_pynq} -quiet] -quiet

# IP: bd/design_pynq/ip/design_pynq_CHOICE_PUF_gen_0_0/design_pynq_CHOICE_PUF_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pynq_CHOICE_PUF_gen_0_0 || ORIG_REF_NAME==design_pynq_CHOICE_PUF_gen_0_0} -quiet] -quiet

# IP: bd/design_pynq/ip/design_pynq_PUF_controller_0_0/design_pynq_PUF_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pynq_PUF_controller_0_0 || ORIG_REF_NAME==design_pynq_PUF_controller_0_0} -quiet] -quiet

# IP: bd/design_pynq/ip/design_pynq_processing_system7_0_0/design_pynq_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pynq_processing_system7_0_0 || ORIG_REF_NAME==design_pynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_pynq/ip/design_pynq_xbar_0/design_pynq_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pynq_xbar_0 || ORIG_REF_NAME==design_pynq_xbar_0} -quiet] -quiet

# IP: bd/design_pynq/ip/design_pynq_ps7_0_axi_periph_0/design_pynq_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_pynq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_pynq/ip/design_pynq_read_adapter_0_0/design_pynq_read_adapter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pynq_read_adapter_0_0 || ORIG_REF_NAME==design_pynq_read_adapter_0_0} -quiet] -quiet

# IP: bd/design_pynq/ip/design_pynq_rst_ps7_0_50M_0/design_pynq_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_pynq_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_pynq/ip/design_pynq_write_adapter_0_0/design_pynq_write_adapter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pynq_write_adapter_0_0 || ORIG_REF_NAME==design_pynq_write_adapter_0_0} -quiet] -quiet

# IP: bd/design_pynq/ip/design_pynq_xadc_wiz_0_0/design_pynq_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pynq_xadc_wiz_0_0 || ORIG_REF_NAME==design_pynq_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/design_pynq/ip/design_pynq_axi_dma_0_0/design_pynq_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pynq_axi_dma_0_0 || ORIG_REF_NAME==design_pynq_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_pynq/ip/design_pynq_xlconstant_0_0/design_pynq_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pynq_xlconstant_0_0 || ORIG_REF_NAME==design_pynq_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_pynq/ip/design_pynq_auto_pc_0/design_pynq_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_pynq_auto_pc_0 || ORIG_REF_NAME==design_pynq_auto_pc_0} -quiet] -quiet

# XDC: c:/FPGA/CHOICE-PUF/CHOICE_design/CHOICE_design.gen/sources_1/bd/design_pynq/design_pynq_ooc.xdc
